backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "exposition"
    label: "Exposition"
    folder: "content/exposition"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Titre de la section",
          name: "section_title",
          widget: "string",
        }
      - {
          label: "Description de la section",
          name: "section_description",
          widget: "text",
        }
      - label: "Catégories"
        name: "categories"
        widget: "list"
        fields:
          - {
              label: "Nom de la catégorie",
              name: "category_name",
              widget: "string",
            }
      - label: "Produits"
        name: "products"
        widget: "list"
        fields:
          - {
              label: "Titre du produit",
              name: "product_title",
              widget: "string",
            }
          - {
              label: "Image du produit",
              name: "product_image",
              widget: "image",
            }
          - {
              label: "Prix du produit",
              name: "product_price",
              widget: "number",
              value_type: "float",
              suffix: "$",
            }
          - {
              label: "Description du produit",
              name: "product_description",
              widget: "text",
            }
